"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './providers';    

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
  // return (
  //   <html lang="en">
  //     <body className={inter.className}>{children}</body>
  //   </html>
  // )
}
